apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  namespace: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      securityContext:
        fsGroup: 1000   # let the container write /opt/emqx/data on the PVC
      containers:
        - name: emqx
          image: emqx/emqx-enterprise:5.10.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
            - name: ws
              containerPort: 8083
            - name: dashboard
              containerPort: 18083
          env:
            # Single-node, HTTP dashboard, WS listener; TLS is terminated at Ingress.
            - name: EMQX_LISTENERS__TCP__DEFAULT__BIND
              value: "0.0.0.0:1883"
            - name: EMQX_LISTENERS__WS__DEFAULT__BIND
              value: "0.0.0.0:8083"
            - name: EMQX_DASHBOARD__LISTENERS__HTTP__BIND
              value: "0.0.0.0:18083"
            - name: EMQX_DASHBOARD__LISTENERS__HTTPS__ENABLE
              value: "false"

            # Dashboard default admin user/pass (first boot)
            - name: EMQX_DASHBOARD__DEFAULT_USERNAME
              value: "admin"
            - name: EMQX_DASHBOARD__DEFAULT_PASSWORD
              value: "NewStrongPass!"

            # Static node name so data on PVC is reused across restarts
            - name: EMQX_NODE__NAME
              value: "emqx@emqx.emqx.svc.cluster.local"
            - name: EMQX_NODE__COOKIE
              value: "emqx-cookie"

          volumeMounts:
            - name: data
              mountPath: /opt/emqx/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: emqx-data
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: emqx
spec:
  type: ClusterIP
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: ws
      port: 8083
      targetPort: 8083
    - name: dashboard
      port: 18083
      targetPort: 18083
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-data
  namespace: emqx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi

