apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: kafka-consumer-pgsql
  namespace: bpclapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-19T11:25:03Z"
      creationTimestamp: null
      labels:
        app: python-app
    spec:
      containers:
      - args:
        - -c
        - pip install --no-cache-dir confluent-kafka psycopg2-binary && python /app/consumer.py
        command:
        - /bin/bash
        image: python:3.11-slim
        imagePullPolicy: IfNotPresent
        name: python-container
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/consumer.py
          name: script-volume
          subPath: consumer.py
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kafka-consumer-script
        name: script-volume
