apiVersion: batch/v1
kind: CronJob
metadata:
  name: kibana-alert-mailer
  namespace: elk
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - pip install --no-cache-dir requests && python /app/send_alert_email.py
            command:
            - sh
            - -c
            env:
            - name: ES_INDEX
              value: alerts-hg-tech-notifications
            - name: LOOKBACK_MINUTES
              value: "10"
            - name: CLUSTER
              value: hg-tech
            - name: ES_CA_CERT
              value: /etc/es-certs/ca.crt
            envFrom:
            - secretRef:
                name: alert-mailer-secrets
            image: python:3.11-slim
            imagePullPolicy: IfNotPresent
            name: mailer
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /app
              name: script
            - mountPath: /etc/es-certs
              name: elastic-ca
              readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: alert-mailer-script
            name: script
          - name: elastic-ca
            secret:
              defaultMode: 420
              secretName: elastic-cert
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 2
  suspend: false
