apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: elk
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logstash
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-01-09T12:32:44+05:30"
      creationTimestamp: null
      labels:
        app: logstash
    spec:
      containers:
      - env:
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: elasticsearch-master-credentials
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: elasticsearch-master-credentials
        image: docker.elastic.co/logstash/logstash:8.5.1
        imagePullPolicy: IfNotPresent
        name: logstash
        ports:
        - containerPort: 5044
          name: beats
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline/logstash.conf
          name: logstash-pipeline
          subPath: logstash.conf
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: logstash-config
          subPath: logstash.yml
        - mountPath: /usr/share/logstash/config/certs
          name: elastic-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: logstash-config
        name: logstash-config
      - name: elastic-cert
        secret:
          defaultMode: 420
          secretName: elastic-cert
      - configMap:
          defaultMode: 420
          name: logstash-pipeline
        name: logstash-pipeline
